#!/usr/bin/env bash
# Автонастройка FreePBX под РФ без GUI (Debian 12 + FreePBX 17, PJSIP)
# ЯЗЫК, КОДЕКИ, НОРМАЛИЗАЦИЯ НОМЕРОВ (+7), ФАЙЕРВОЛ (опционально)
set -euo pipefail

OPEN_UFW="${OPEN_UFW:-no}"                  # yes|no — открыть порты UFW (если пользуешь FreePBX Firewall, оставь no)
CODECS="${CODECS:-alaw,opus,g729,ulaw}"     # желаемый порядок кодеков
LANG="${LANG:-ru}"                          # язык звонков
LOG="/root/fbx-cli-setup-ru.log"

echo "==> Автонастройка FreePBX без GUI" | tee -a "$LOG"

# 1) Русские тоны и системные звуки (если ещё не стояли)
echo "==> Включаю country=ru и ставлю RU звуки..." | tee -a "$LOG"
INC="/etc/asterisk/indications.conf"
if [[ -f "$INC" ]]; then
  sed -ri 's/^country=.*/country=ru/' "$INC" || true
  grep -q '^country=' "$INC" || sed -i '1i [general]\ncountry=ru\n' "$INC"
else
  printf "[general]\ncountry=ru\n" > "$INC"
fi
apt-get update -y >>"$LOG" 2>&1 || true
apt-get install -y asterisk-core-sounds-ru asterisk-core-sounds-ru-wav \
                    asterisk-core-sounds-ru-gsm asterisk-core-sounds-ru-g722 >>"$LOG" 2>&1 || true

# 2) Язык по умолчанию на звонках (диалплан-хук, не перетирается FreePBX)
#    from-internal-custom — срабатывает для внутренних вызовов
#    from-pstn-custom     — для входящих с транков
echo "==> Включаю язык ${LANG} в диалплане (from-internal-custom / from-pstn-custom)..." | tee -a "$LOG"
EXTC="/etc/asterisk/extensions_custom.conf"
touch "$EXTC"
grep -q '\[from-internal-custom\]' "$EXTC" || cat >>"$EXTC" <<'EOF'

[from-internal-custom]
; Устанавливаем язык для внутренних исходящих
exten => _X.,1,Set(CHANNEL(language)=ru)
same  => n,Return()

[from-pstn-custom]
; Устанавливаем язык для входящих с транков
exten => s,1,Set(CHANNEL(language)=ru)
same  => n,Return()
EOF
# Если хочешь другой язык — перед запуском установи LANG=ru|en и т.д.

# 3) Нормализация исходящих номеров под РФ (8XXXXXXXXXX -> 7XXXXXXXXXX) до маршрутов
#    Хук outrt-pre-hook — выполняется до Outbound Routes
echo "==> Добавляю нормализацию 8XXXXXXXXXX -> 7XXXXXXXXXX (outrt-pre-hook)..." | tee -a "$LOG"
grep -q '\[outrt-pre-hook\]' "$EXTC" || cat >>"$EXTC" <<'EOF'

[outrt-pre-hook]
; Если набрали 11 цифр, начинающихся на 8 — заменим 8 на 7 (E.164 для РФ)
exten => _8XXXXXXXXXX,1,NoOp(Normalize: 8XXXXXXXXXX -> 7XXXXXXXXXX)
 same => n,Set(TO_DIAL=${EXTEN})
 same => n,Set(TO_DIAL=7${TO_DIAL:1})
 same => n,Goto(app-blackhole,hangup,1) ; заглушка, чтобы не звонило не туда
; Возврат к маршрутам — используем новый номер:
; FreePBX перехватит номер повторно через LOCAL/LOCAL, поэтому хитрым способом:
exten => _7XXXXXXXXXX,1,Return()
EOF
# Пояснение: hook объявляет шаблон и возвращает управление в маршрутизацию уже с "7..."
# Если провайдер требует "+7", меняй на prepend +7 и дальнейшее удаление 7.

# 4) Кодеки и язык на всех текущих PJSIP endpoint'ах и транках
#    Сгенерируем pjsip.endpoint_custom_post.conf с блоками (+type=endpoint)
#    для каждого существующего endpoint'а, чтобы задать allow= и language=.
echo "==> Выставляю кодеки (${CODECS}) и язык (${LANG}) на всех PJSIP endpoint'ах..." | tee -a "$LOG"
OUT="/etc/asterisk/pjsip.endpoint_custom_post.conf"

# Сохраним бэкап и шапку
cp -a "$OUT" "${OUT}.bak.$(date +%F-%H%M%S)" 2>/dev/null || true
printf "; autogenerated by fbx_cli_setup_ru.sh on %s\n" "$(date)" > "$OUT"

# Получаем список endpoint'ов из Asterisk
ENDPOINTS=$(asterisk -rx "pjsip show endpoints" | awk '/Endpoint: /{print $2}' | sed 's/[^A-Za-z0-9_\-\.]//g' | sort -u)

if [[ -z "${ENDPOINTS}" ]]; then
  echo "   Не найдено endpoint'ов (создай хотя бы одно расширение/транк и перезапусти скрипт)." | tee -a "$LOG"
else
  for E in $ENDPOINTS; do
    cat >>"$OUT" <<EOF
[${E}](+type=endpoint)
allow=${CODECS}
language=${LANG}
EOF
  done
fi

chown asterisk:asterisk "$OUT" || true

# 5) Перечитать конфиг
echo "==> Перечитываю конфиг Asterisk..." | tee -a "$LOG"
fwconsole reload >>"$LOG" 2>&1 || systemctl restart asterisk

# 6) Файервол (опционально UFW). Если пользуешься FreePBX Firewall — лучше оставить no.
if [[ "$OPEN_UFW" == "yes" ]]; then
  echo "==> Открываю порты UFW (80,443 TCP; 5060/udp|tcp; 5061/tcp; RTP 10000-20000/udp; UCP 8001,8003)..." | tee -a "$LOG"
  apt-get install -y ufw >>"$LOG" 2>&1 || true
  ufw allow OpenSSH
  ufw allow 80,443/tcp
  ufw allow 5060/udp
  ufw allow 5060/tcp
  ufw allow 5061/tcp
  ufw allow 10000:20000/udp
  ufw allow 8001,8003/tcp
  yes | ufw enable
fi

echo "==> Готово."
echo "Проверка:"
echo "  asterisk -rx 'core show settings' | grep -i country"
echo "  asterisk -rx 'pjsip show endpoint <EXT>' | egrep 'allow|language'"
echo "  asterisk -rx 'dialplan show outrt-pre-hook' | sed -n '1,120p'"
