#!/usr/bin/env bash
# ALL-IN-ONE: FreePBX 17 (Debian 12) + RU-телефония + CLI-настройки без GUI
# 1) Установка FreePBX (офиц. скрипт), 2) chrony+country=ru+sounds+NAT, 3) кодеки/язык/нормализация 8->7
set -euo pipefail

### Параметры
TIMEZONE="${TIMEZONE:-Europe/Moscow}"
INSTALL_DAHDI="${INSTALL_DAHDI:-no}"   # yes|no
ENABLE_UFW="${ENABLE_UFW:-no}"         # yes|no — (лучше no, если используешь FreePBX Firewall)
USE_RU_LOCALE="${USE_RU_LOCALE:-no}"   # yes|no — системная локаль ru_RU.UTF-8 (по умолчанию нет)
CODECS="${CODECS:-alaw,opus,g729,ulaw}"
LANG="${LANG:-ru}"

log() { echo -e "==> $*"; }

[[ $EUID -eq 0 ]] || { echo "Запусти от root"; exit 1; }
grep -q 'ID=debian' /etc/os-release && grep -q 'VERSION_ID="12' /etc/os-release || { echo "Нужен Debian 12 (bookworm)"; exit 1; }

export DEBIAN_FRONTEND=noninteractive

### 1) FreePBX 17
log "Установка FreePBX 17 на Debian 12..."
apt-get update -y
apt-get full-upgrade -y
apt-get install -y curl wget ca-certificates gnupg lsb-release net-tools iproute2 htop logrotate tzdata

cd /tmp
wget -q https://github.com/FreePBX/sng_freepbx_debian_install/raw/master/sng_freepbx_debian_install.sh -O sng_freepbx_debian_install.sh
chmod +x sng_freepbx_debian_install.sh
ARGS=""
[[ "$INSTALL_DAHDI" == "yes" ]] && ARGS+=" --dahdi"
bash ./sng_freepbx_debian_install.sh ${ARGS} | tee /root/freepbx-wrapper.log

systemctl enable --now asterisk apache2 mariadb || true
if systemctl list-unit-files | grep -q fail2ban.service; then systemctl enable --now fail2ban || true; fi

### 2) РФ-локализация телефонии (chrony, тоны, звуки, NAT)
log "РФ-локализация телефонии (chrony, тоны, звуки, NAT)..."
timedatectl set-timezone "$TIMEZONE" || true
apt-get install -y dnsutils curl ca-certificates chrony
if grep -qE '^\s*pool\s+' /etc/chrony/chrony.conf; then
  sed -ri 's|^\s*pool\s+.*|pool ru.pool.ntp.org iburst|' /etc/chrony/chrony.conf
else
  echo "pool ru.pool.ntp.org iburst" >> /etc/chrony/chrony.conf
fi
systemctl enable --now chrony || true
[[ "$USE_RU_LOCALE" == "yes" ]] && { apt-get install -y locales; sed -ri 's/^# ?(ru_RU\.UTF-8 UTF-8)/\1/' /etc/locale.gen; locale-gen ru_RU.UTF-8; update-locale LANG=ru_RU.UTF-8; }

INC="/etc/asterisk/indications.conf"
if [[ -f "$INC" ]]; then
  if grep -q '^country=' "$INC"; then sed -ri 's/^country=.*/country=ru/' "$INC"; else sed -i '1i [general]\ncountry=ru\n' "$INC"; fi
else
  printf "[general]\ncountry=ru\n" > "$INC"
fi
apt-get install -y asterisk-core-sounds-ru asterisk-core-sounds-ru-wav asterisk-core-sounds-ru-gsm asterisk-core-sounds-ru-g722 || true

PUBIP="$(dig +short myip.opendns.com @resolver1.opendns.com || true)"; [[ -z "$PUBIP" ]] && PUBIP="$(curl -4 -s https://ifconfig.co || true)"; [[ -z "$PUBIP" ]] && PUBIP="$(curl -4 -s https://icanhazip.com || true)"
PJ_CUSTOM="/etc/asterisk/pjsip.transports_custom_post.conf"
if [[ -n "$PUBIP" ]]; then
  cat > "$PJ_CUSTOM" <<EOF
[0.0.0.0-udp](+type=transport)
external_signaling_address=$PUBIP
external_media_address=$PUBIP
EOF
  chown asterisk:asterisk "$PJ_CUSTOM" || true
  log "Внешний IP: $PUBIP"
else
  log "Не удалось autodetect внешнего IP — заполни вручную в GUI: Asterisk SIP Settings."
fi

### 3) CLI‑настройки: кодеки/язык на endpoint’ах и нормализация 8->7
log "Проставляю language=${LANG} и allow=${CODECS} на endpoint’ах..."
OUT="/etc/asterisk/pjsip.endpoint_custom_post.conf"
cp -a "$OUT" "${OUT}.bak.$(date +%F-%H%M%S)" 2>/dev/null || true
printf "; autogenerated by freepbx_ru_all_in_one on %s\n" "$(date)" > "$OUT"
ENDPOINTS=$(asterisk -rx "pjsip show endpoints" | awk '/^Endpoint: /{print $2}' | sed 's/[^A-Za-z0-9_.\-]//g' | sort -u)
for E in $ENDPOINTS; do
  cat >>"$OUT" <<EOF
[${E}](+type=endpoint)
allow=${CODECS}
language=${LANG}
EOF
done
chown asterisk:asterisk "$OUT" || true

EXTC="/etc/asterisk/extensions_custom.conf"
touch "$EXTC"
if ! grep -q '^\[sub-dialout-trunk-predial-hook\]' "$EXTC"; then
  cat >>"$EXTC" <<'EOF'

[sub-dialout-trunk-predial-hook]
exten => s,1,NoOp(Normalize RU: 8XXXXXXXXXX -> 7XXXXXXXXXX)
 same => n,Set(OUTNUM=${IF($["${OUTNUM:0:1}"="8"]?7${OUTNUM:1}:${OUTNUM})})
 same => n,Return()

[macro-dialout-trunk-predial-hook]
exten => s,1,NoOp(Normalize RU (macro))
 same => n,Set(OUTNUM=${IF($["${OUTNUM:0:1}"="8"]?7${OUTNUM:1}:${OUTNUM})})
 same => n,MacroExit()
EOF
fi

### 4) Перечитать конфиг и (опц.) UFW
fwconsole reload || systemctl restart asterisk
if [[ "$ENABLE_UFW" == "yes" ]]; then
  apt-get install -y ufw
  ufw allow OpenSSH
  ufw allow 80,443/tcp
  ufw allow 5060/udp
  ufw allow 5060/tcp
  ufw allow 5061/tcp
  ufw allow 10000:20000/udp
  ufw allow 8001,8003/tcp
  yes | ufw enable
fi

log "Готово. Проверь:"
echo "  asterisk -rx 'core show version' ; fwconsole --version"
echo "  asterisk -rx 'core show settings' | grep -i country"
echo "  asterisk -rx 'pjsip show transports' ; asterisk -rx 'pjsip show endpoint <EXT>' | egrep 'allow|language'"
